export type ToolCategory =
  'converter' | 'text' | 'crypto' | 'web' | 'development' | 'math' | 'generator' | 'fun';

export interface ToolMeta {
  /** URL segment and prerender filename — must match the folder name. */
  id: string;
  icon: string;
  category: ToolCategory;
  /** i18n key stem: tools.<key>.name / .description */
  key: string;
  keywords?: readonly string[];
}

// Catalogue, routes and search share this curated list.
export const TOOLS = [
  {
    id: 'data-workbench',
    icon: 'lucide:braces',
    category: 'converter',
    key: 'dataWorkbench',
    keywords: [
      'JSON',
      'YAML',
      'CSV',
      'TSV',
      'TypeScript',
      'JSON Schema',
      '排序',
      '扁平化',
      'json format',
      'JSON Formatter',
      'JSON 格式化',
      'json to yaml',
      'JSON ⇄ YAML',
      'json to csv',
      'JSON ⇄ CSV',
      'csv to tsv',
      'CSV to TSV',
      'CSV 转 TSV',
      'json flatten',
      'JSON Flattener',
      'JSON 扁平化',
      'json sort keys',
      'JSON Key Sorter',
      'JSON 键排序',
      'json to ts',
      'JSON to TypeScript',
      'JSON 转 TypeScript',
      'json schema generator',
      'JSON Schema Generator',
      'JSON Schema 生成器',
    ],
  },
  {
    id: 'text-codec',
    icon: 'lucide:binary',
    category: 'converter',
    key: 'textCodec',
    keywords: [
      'Base64',
      'Base32',
      'Base58',
      'UTF-8',
      'HEX',
      'URL',
      'HTML',
      'SVG',
      '转义',
      '二进制',
      'base64',
      'Base64 Encode / Decode',
      'Base64 编码 / 解码',
      'base32',
      'Base32 Encode / Decode',
      'Base32 编码 / 解码',
      'base58',
      'Base58 Encode / Decode',
      'Base58 编码 / 解码',
      'hex text',
      'Hex ↔ Text',
      '十六进制 ↔ 文本',
      'text to binary',
      'Text ⇄ Binary',
      '文本 ⇄ 二进制',
      'html entities',
      'HTML Entities',
      'HTML 实体',
      'url encode',
      'URL Encode / Decode',
      'URL 编码 / 解码',
      'string escape',
      'String Escape',
      '字符串转义',
      'svg to data uri',
      'SVG to Data URI',
      'SVG 转 Data URI',
    ],
  },
  {
    id: 'base-converter',
    icon: 'lucide:arrow-left-right',
    category: 'converter',
    key: 'baseConverter',
  },
  {
    id: 'unit-converter',
    icon: 'lucide:ruler',
    category: 'converter',
    key: 'unitConverter',
    keywords: [
      'temperature',
      'length',
      'data size',
      'duration',
      'angle',
      'SI',
      'IEC',
      '温度',
      '长度',
      '数据大小',
      '时长',
      '角度',
      'temperature converter',
      'Temperature Converter',
      '温度转换',
      'length converter',
      'Length Converter',
      '长度转换',
      'data size converter',
      'Data Size Converter',
      '数据大小转换',
      'duration converter',
      'Duration Converter',
      '时长转换',
      'angle converter',
      'Angle Converter',
      '角度转换',
    ],
  },
  {
    id: 'date-time',
    icon: 'lucide:calendar-clock',
    category: 'converter',
    key: 'dateTime',
    keywords: [
      'timestamp',
      'date difference',
      'business days',
      '日期差',
      '时间戳',
      '工作日',
      '年龄',
      'Timestamp Converter',
      '时间戳转换',
      'Date Difference',
      '日期间隔',
      'age calculator',
      'Age Calculator',
      '年龄计算器',
      'Business Days Calculator',
      '工作日计算器',
    ],
  },
  {
    id: 'color-converter',
    icon: 'lucide:palette',
    category: 'converter',
    key: 'colorConverter',
    keywords: [
      'color shades',
      'random color',
      'palette',
      '颜色',
      '色阶',
      '随机颜色',
      'Color Shades',
      '颜色深浅',
      'Random Color',
    ],
  },
  {
    id: 'text-workbench',
    icon: 'lucide:file-text',
    category: 'text',
    key: 'textWorkbench',
    keywords: [
      'case',
      'slug',
      'sort',
      'duplicate',
      'whitespace',
      'line',
      'extract',
      'stats',
      'frequency',
      'normalize',
      '命名',
      '去重',
      '排序',
      '空白',
      '统计',
      '词频',
      '提取',
      '换行',
      'case converter',
      'Case Converter',
      '命名转换',
      'slugify',
      'Slugify',
      'URL 别名',
      'sort lines',
      'Sort Lines',
      '行排序',
      'duplicate lines',
      'Duplicate Line Remover',
      '重复行移除',
      'remove whitespace',
      'Remove Whitespace',
      '清理空白',
      'remove accents',
      'Remove Accents',
      '去除重音符号',
      'line endings',
      'Line Endings',
      '换行符转换',
      'text reverse',
      'Text Reverse',
      '文本反转',
      'line numberer',
      'Line Numberer',
      '行号添加器',
      'text wrap',
      'Text Wrapper',
      '文本自动换行',
      'extract emails',
      'Email Extractor',
      '邮箱提取器',
      'extract urls',
      'URL Extractor',
      '网址提取器',
      'list converter',
      'List Converter',
      '列表格式转换',
      'text stats',
      'Text Statistics',
      '文本统计',
      'word frequency',
      'Word Frequency',
      '词频统计',
      'unicode normalizer',
      'Unicode Normalizer',
      'Unicode 规范化',
      'whitespace visualizer',
      'Whitespace Visualizer',
      '空白字符可视化',
      'find replace',
      'Find & Replace',
      '查找替换',
    ],
  },
  {
    id: 'unicode-inspector',
    icon: 'lucide:type',
    category: 'text',
    key: 'unicodeInspector',
  },
  {
    id: 'regex-tester',
    icon: 'lucide:regex',
    category: 'text',
    key: 'regexTester',
  },
  {
    id: 'text-diff',
    icon: 'lucide:git-compare',
    category: 'text',
    key: 'textDiff',
  },
  {
    id: 'hash-text',
    icon: 'lucide:hash',
    category: 'crypto',
    key: 'hashText',
    keywords: [
      'md5 hash',
      'MD5 Hash',
      'MD5 哈希',
      'crc32',
      'CRC-32',
      'hmac generator',
      'HMAC Generator',
      'HMAC 生成',
    ],
  },
  {
    id: 'jwt-decoder',
    icon: 'lucide:key-square',
    category: 'crypto',
    key: 'jwtDecoder',
  },
  {
    id: 'totp',
    icon: 'lucide:timer',
    category: 'crypto',
    key: 'totp',
  },
  {
    id: 'url-workbench',
    icon: 'lucide:globe',
    category: 'web',
    key: 'urlWorkbench',
    keywords: [
      'query',
      'UTM',
      'URL',
      'relative',
      '查询参数',
      '相对路径',
      'url parser',
      'URL Parser',
      'URL 解析',
      'query json',
      'Query ⇄ JSON',
      '查询串 ⇄ JSON',
      'url joiner',
      'URL Joiner',
      '网址拼接器',
      'utm builder',
      'UTM URL Builder',
      'UTM 链接生成器',
      'punycode',
      'Punycode',
    ],
  },
  {
    id: 'http-inspector',
    icon: 'lucide:rows-3',
    category: 'web',
    key: 'httpInspector',
    keywords: [
      'HTTP',
      'headers',
      'cookies',
      'Basic Auth',
      '请求头',
      'http headers parser',
      'HTTP Headers Parser',
      'HTTP 头解析器',
      'cookie parser',
      'Cookie Parser',
      'Cookie 解析器',
      'basic auth',
      'Basic Auth Header',
      'Basic 认证头',
    ],
  },
  {
    id: 'ipv4-subnet',
    icon: 'lucide:network',
    category: 'web',
    key: 'ipv4Subnet',
    keywords: ['ip converter', 'IP Converter', 'IP 转换'],
  },
  {
    id: 'unix-permission',
    icon: 'lucide:shield',
    category: 'development',
    key: 'unixPermission',
  },
  {
    id: 'css-gradient',
    icon: 'lucide:paintbrush',
    category: 'development',
    key: 'cssGradient',
  },
  {
    id: 'box-shadow',
    icon: 'lucide:box',
    category: 'development',
    key: 'boxShadow',
  },
  {
    id: 'crontab-parser',
    icon: 'lucide:calendar-clock',
    category: 'development',
    key: 'crontabParser',
  },
  {
    id: 'meta-tags',
    icon: 'lucide:tags',
    category: 'development',
    key: 'metaTags',
  },
  {
    id: 'docker-run-to-compose',
    icon: 'lucide:container',
    category: 'development',
    key: 'dockerRunToCompose',
  },
  {
    id: 'gitignore-generator',
    icon: 'lucide:git-branch',
    category: 'development',
    key: 'gitignoreGenerator',
  },
  {
    id: 'statistics',
    icon: 'lucide:sigma',
    category: 'math',
    key: 'statistics',
  },
  {
    id: 'identifiers',
    icon: 'lucide:fingerprint',
    category: 'generator',
    key: 'identifiers',
    keywords: [
      'UUID',
      'ULID',
      'NanoID',
      'UUID Inspector',
      '标识符',
      'uuid',
      'UUID Generator',
      'UUID 生成器',
      'ulid',
      'ULID Generator',
      'ULID 生成器',
      'nanoid',
      'Nano ID Generator',
      'Nano ID 生成器',
      'uuid inspector',
      'UUID 检查器',
    ],
  },
  {
    id: 'secret-generator',
    icon: 'lucide:key',
    category: 'generator',
    key: 'secretGenerator',
    keywords: [
      'password',
      'key',
      'token',
      'random string',
      '密码',
      '密钥',
      '令牌',
      '随机字符串',
      'password generator',
      'Password Generator',
      '密码生成',
      'key generator',
      'Key Generator',
      '密钥生成',
      'Random String',
    ],
  },
  {
    id: 'random-number',
    icon: 'lucide:dices',
    category: 'generator',
    key: 'randomNumber',
  },
  {
    id: 'qrcode',
    icon: 'lucide:qr-code',
    category: 'generator',
    key: 'qrcode',
  },
  {
    id: 'placeholder-image',
    icon: 'lucide:image-plus',
    category: 'generator',
    key: 'placeholderImage',
  },
  {
    id: 'cps-test',
    icon: 'lucide:mouse-pointer-click',
    category: 'fun',
    key: 'cpsTest',
  },
  {
    id: 'reaction-time',
    icon: 'lucide:zap',
    category: 'fun',
    key: 'reactionTime',
  },
  {
    id: 'typing-speed',
    icon: 'lucide:type',
    category: 'fun',
    key: 'typingSpeed',
  },
] as const satisfies readonly ToolMeta[];

export const CATEGORY_ORDER: ToolCategory[] = [
  'converter',
  'text',
  'crypto',
  'web',
  'development',
  'math',
  'generator',
  'fun',
];
